### ISSUE TITLE
Notification Reminder for Task

### ISSUE THREAD

**Issue by Spikeysanju** [Spikeysanju/Einsen#49]
The goal of this feature request is to Add Notification Reminder for the task. Current implementation doesn't have that feature yet.

**Comment by yogeshpaliyal** [comment]
@Spikeysanju I would like to work on this.

**Comment by Spikeysanju** [comment]
@yogeshpaliyal Thanks for your interest. You can pickup this task 😃 👍 

### 💡 Solution I've considered
Currently we have this `Due Date` field in our model class. But we're not collecting `Due Date & Time` from the `frontend`. 

The goal of this task is to add another `datepicker field` on `Add Task & Edit Task Screen`. 

After that we need to `show notification` to user based on the `due date`.

**🎯 Action Items**
1. Add `Date & Time Picker` Field
2. Show `notification` to user

---

P.S - If you have any alternative solution kindly please let me know. Thanks in advance.

**Comment by yogeshpaliyal** [comment]
@Spikeysanju 
What will be trigger for notifications.
Like 1 day earlier, 1 hr. Earlier.

**Comment by Spikeysanju** [comment]
@yogeshpaliyal IMO `1hr Earlier` would work. Any thought from your side?

**Comment by yogeshpaliyal** [comment]
I think we can add 2 notifications first one is 1 hour prior and second 5 minutes prior.

**Comment by Spikeysanju** [comment]
Sounds good to me. Please proceed 🙌

**Comment by Spikeysanju** [comment]
@yogeshpaliyal  PR merged 🚀 . This is huge. Thanks for your valuable contribution 🥇 . Have a great day!

**Comment by yogeshpaliyal** [comment]
Thanks @Spikeysanju
