### ISSUE TITLE
Emoji chooser bottom sheet search option

### ISSUE THREAD

**Issue by SachinKasaraddi** [Spikeysanju/Einsen#75]
**Its hard to select task related emoji**
Currently user has to scroll through all emojis and find the related one.

**Search input field in `AllEmojiScreen`**
In the search field user will enter the search term, which can queried against `description` or `aliases` from emoji list.
This way user can select emojis related to task.

**Comment by Spikeysanju** [comment]
@SachinKasaraddi  Added `Search` for the Emoji Chooser Bottom Sheet. But still I didn't add `sticky header` because currently Jetpack Compose `LazyVerticalGrid` doesn't support the `sticky header` feature. I will be implementing this once we have that support. 

Thanks for bringing up this 🙌

**Comment by SachinKasaraddi** [comment]
@Spikeysanju 
Actually the intention of raising this issue was to contribute to this project. 
But never mind now, I will have 👁️ on some more cool things to contribute to this app 👍
