### ISSUE TITLE
Task added to inappropriate Section

### ISSUE THREAD

**Issue by yogeshpaliyal** [Spikeysanju/Einsen#80]
**Describe the bug**
I've added a task with urgency 2 and importance 0, but it it showing in *Do it Now*

**Screenshots**
https://user-images.githubusercontent.com/9381846/138202306-de21a1f1-b3d4-4f93-8b81-836cae8cb377.mp4

**Smartphone Details:**
 - Mobile Mi note 10 Pro Max (Pixel Experience)
 - Version : Android 11

**Comment by Spikeysanju** [comment]
@yogeshpaliyal I checked the app on my device `Poco F1` (Android 11). But it seems like working for me. Did you tried the `latest apk` from the release?

Because 2 days back I've fixed this issue  👉 #73  . Please let me know. Thanks in advance.
